export const policies = [
  { id: 'POL-01', title: 'Document image quality', section: '2.1', text: 'If glare, blur, or a cropped edge prevents document reading, request a new capture with all four corners visible and no reflections. After three failed capture attempts, route to a specialist instead of requesting another retry.', signals: ['IMAGE_GLARE', 'IMAGE_BLUR', 'DOCUMENT_CROPPED'], action: 'Request a new document photo', reply: 'The document photo could not be read clearly. Please take a new photo in even lighting, without flash, with all four corners visible.' },
  { id: 'POL-02', title: 'Expired documents', section: '2.2', text: 'An expired document cannot be used in this demo verification flow. Request a current supported identity document. Support must not override document validity.', signals: ['DOCUMENT_EXPIRED'], action: 'Request a current document', reply: 'The document submitted has expired. Please restart verification using a current passport, driver’s license, or national ID supported by this flow.' },
  { id: 'POL-03', title: 'Name discrepancies', section: '3.1', text: 'A name mismatch requires specialist review. Do not change account identity details or approve verification based on a support conversation. Route the discrepancy through the secure review process.', signals: ['NAME_MISMATCH'], action: 'Escalate the name discrepancy', reply: 'The name on the document differs from the account information. We will route this case to a verification specialist for review through the secure process.' },
  { id: 'POL-04', title: 'Supported document types', section: '2.3', text: 'This mock flow supports passports, driver’s licenses, and national IDs. Student IDs and other unsupported documents require a new submission using a supported type. Do not infer country eligibility from document type alone.', signals: ['UNSUPPORTED_DOCUMENT'], action: 'Request a supported document', reply: 'This verification flow does not support the document type submitted. Please use a current passport, driver’s license, or national ID offered in the verification screen.' },
  { id: 'POL-05', title: 'Selfie and liveness capture', section: '4.1', text: 'For a failed liveness capture, allow a guided retry with adequate lighting and an unobstructed camera when fewer than three attempts have failed. Three or more failed attempts require specialist review. A failed capture alone is not evidence of fraud.', signals: ['LIVENESS_FAILED', 'CAMERA_BLOCKED'], action: 'Offer a guided selfie retry', reply: 'The selfie check did not complete. Please allow camera access, use even lighting, and keep your face fully in frame before trying again.' },
  { id: 'POL-06', title: 'Session interruptions', section: '5.1', text: 'An expired session or interrupted connection can be restarted using the secure verification flow. Never ask the user to email identity documents. Repeated failures at three or more attempts require specialist review.', signals: ['SESSION_EXPIRED', 'NETWORK_INTERRUPTED'], action: 'Restart the secure session', reply: 'The verification session was interrupted. Please return to the secure verification screen and start a new session with a stable connection.' },
  { id: 'POL-07', title: 'Uncertain or conflicting evidence', section: '6.1', text: 'If an error code is unknown, absent, or conflicts with other evidence, do not guess the cause. Escalate for specialist diagnosis. Do not approve identity verification or assert fraud from incomplete evidence.', signals: [], action: 'Escalate for diagnosis', reply: 'We could not determine why the verification stopped. We will route this case to a specialist to investigate the available verification records.' },
  { id: 'POL-08', title: 'Retry limit', section: '6.2', text: 'Three or more failed verification attempts require specialist review before any further retry. This rule takes precedence over routine retry guidance. Support cannot bypass or reset the retry limit.', signals: [], action: 'Escalate repeated failures', reply: 'The verification has failed several times. We will route this case to a specialist before asking you to try again.' }
];

export const cases = [
  { id: 'VC-1041', name: 'Jordan Lee', initials: 'JL', document: 'Driver’s license', country: 'United States', attempts: 1, signal: 'IMAGE_GLARE', message: 'I uploaded my license, but it keeps saying it can’t read it. What should I do?', note: 'Reflection covers the document number. All four corners are visible.', age: '4 min', priority: 'Normal' },
  { id: 'VC-1042', name: 'Alex Morgan', initials: 'AM', document: 'Passport', country: 'Canada', attempts: 1, signal: 'DOCUMENT_EXPIRED', message: 'My passport is the only ID I have nearby. Why won’t it go through?', note: 'Document validity check returned expired.', age: '8 min', priority: 'Normal' },
  { id: 'VC-1043', name: 'Sam Rivera', initials: 'SR', document: 'National ID', country: 'Spain', attempts: 2, signal: 'NAME_MISMATCH', message: 'My account has my old last name. Can you just update it for me?', note: 'Account surname and document surname differ.', age: '12 min', priority: 'Review' },
  { id: 'VC-1044', name: 'Taylor Chen', initials: 'TC', document: 'Passport', country: 'United States', attempts: 3, signal: 'LIVENESS_FAILED', message: 'I’ve done the selfie three times. Can someone help me finish?', note: 'Three incomplete liveness captures; no identity decision returned.', age: '16 min', priority: 'Review' },
  { id: 'VC-1045', name: 'Casey Patel', initials: 'CP', document: 'Student ID', country: 'United Kingdom', attempts: 1, signal: 'UNSUPPORTED_DOCUMENT', message: 'I used my university card. Is that not enough?', note: 'Submitted document type is outside the mock supported list.', age: '21 min', priority: 'Normal' },
  { id: 'VC-1046', name: 'Riley Brooks', initials: 'RB', document: 'Driver’s license', country: 'United States', attempts: 1, signal: 'SESSION_EXPIRED', message: 'I switched apps to find my ID and the link stopped working.', note: 'Verification session timed out before submission.', age: '24 min', priority: 'Normal' },
  { id: 'VC-1047', name: 'Jamie Park', initials: 'JP', document: 'Passport', country: 'South Korea', attempts: 1, signal: 'CAMERA_BLOCKED', message: 'The selfie screen is blank. I can’t get it to open my camera.', note: 'Browser camera permission was denied.', age: '28 min', priority: 'Normal' },
  { id: 'VC-1048', name: 'Drew Ellis', initials: 'DE', document: 'National ID', country: 'Germany', attempts: 1, signal: 'UNKNOWN_ERROR', message: 'It just says something went wrong, with no explanation.', note: 'No recognized provider error code in the session.', age: '32 min', priority: 'Review' },
  { id: 'VC-1049', name: 'Avery James', initials: 'AJ', document: 'Driver’s license', country: 'United States', attempts: 3, signal: 'IMAGE_BLUR', message: 'I tried three clearer pictures and none of them worked.', note: 'Three failed image-quality checks.', age: '35 min', priority: 'Review' },
  { id: 'VC-1050', name: 'Quinn Santos', initials: 'QS', document: 'Passport', country: 'Brazil', attempts: 2, signal: 'NETWORK_INTERRUPTED', message: 'The upload got to the end and then my connection dropped.', note: 'Upload did not complete; no verification result exists.', age: '41 min', priority: 'Normal' }
];

export const labels = { IMAGE_GLARE: 'Document glare', IMAGE_BLUR: 'Blurry document', DOCUMENT_CROPPED: 'Cropped document', DOCUMENT_EXPIRED: 'Expired document', NAME_MISMATCH: 'Name discrepancy', UNSUPPORTED_DOCUMENT: 'Unsupported document', LIVENESS_FAILED: 'Incomplete liveness check', CAMERA_BLOCKED: 'Camera access blocked', SESSION_EXPIRED: 'Session expired', NETWORK_INTERRUPTED: 'Connection interrupted', UNKNOWN_ERROR: 'Unknown failure' };
